const SET_FILE_PATHS = 'SET_FILE_PATHS';
const SET_CURRENT_IMG = 'SET_CURRENT_IMG';
const SET_DOWNLOADED_EXTS = 'SET_DOWNLOADED_EXTS';
const SET_VIEWER_DIMENSIONS = 'SET_VIEWER_DIMENSIONS';
const NAVIGATE_TO_IMG = 'NAVIGATE_TO_IMG';
const ADD_CANVAS_REF = 'ADD_CANVAS_REF';
const SHOW_HIDE_FILES = 'SHOW_HIDE_FILES';
const REGISTER_NEW_EXTENSION = 'REGISTER_NEW_EXTENSION';
const ACTIVATE_LAYER =  'ACTIVATE_LAYER';
const CLOSE_EXTENSION = 'CLOSE_EXTENSION';
const UPDATE_IMAGES = 'UPDATE_IMAGES';
module.exports = {
  SET_FILE_PATHS,
  SET_CURRENT_IMG,
  SET_DOWNLOADED_EXTS,
  SET_VIEWER_DIMENSIONS,
  NAVIGATE_TO_IMG,
  ADD_CANVAS_REF,
  SHOW_HIDE_FILES,
  REGISTER_NEW_EXTENSION,
  ACTIVATE_LAYER,
  CLOSE_EXTENSION,
  UPDATE_IMAGES,
};
